default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  port: 5432
  host: postgres

development:
  <<: *default
  database: speakerinnen_development
  password: postgres
  username: postgres

test:
  <<: *default
  database: speakerinnen_test
  password: postgres
  username: postgres

staging:
  <<: *default
  database: YOUR-DATABASE-NAME
  password: YOUR-DATABASE-USERNAME-PASSWORD

production:
  <<: *default
  database: YOUR-DATABASE-NAME
  password: YOUR-DATABASE-USERNAME-PASSWORD
